project_name: cardkey-web
server:
  host: 118.196.24.101
  user: hhx
  repo_path: /root/cardkey-web
  port: 22
  key_file: ~/.ssh/id_ed25519
  runner_exec: /root/cicd-tool/.venv/bin/cicd-runner
environments:
  prod:
    deploy_path: /var/www/cardkey-web
    steps:
    - npm install
    - npm run build
    - rm -rf {deploy_path}/*
    - cp -r dist/* {deploy_path}
    - action: nginx
  test:
    deploy_path: /data/repos/cardkey-web/dist
    steps:
    - npm install
    - npm run build:test
  dev:
    deploy_path: /data/repos/cardkey-web/dist
    steps:
    - npm install
    - npm run build:dev
